In [25]:
import pandas as pd

In [27]:
import os

os.chdir('/Users/rowena/Other Projects/external_data_study/Result/Government Contract Extraction/gov_cntract/Raw/data')

In [118]:
df_epd=pd.read_json('gov_epd.json',lines=True)

In [120]:
df_epd_tmp=df_epd[["ref","department","description","awardee","award_date",	"sum","period","url"]]

In [146]:
from datetime import datetime

df_epd_tmp['award_date1']=''

for i in range(len(df_epd_tmp)):
    if len(df_epd_tmp.loc[i,'award_date'])==8:
        df_epd_tmp.loc[i,'award_date1']=datetime.strptime(df_epd_tmp.loc[i,'award_date'], "%b %Y")
    elif len(df_epd_tmp.loc[i,'award_date'])>8:
        try:
            df_epd_tmp.loc[i,'award_date1']=datetime.strptime(df_epd_tmp.loc[i,'award_date'], "%B %Y")
        except:
            pass

/var/folders/cc/fgdvcyz155z2b_s9qh66r2pw0000gn/T/ipykernel_2015/1394147320.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_epd_tmp['award_date1']=''

In [150]:
df_epd_tmp['award_date']=df_epd_tmp['award_date1']

/var/folders/cc/fgdvcyz155z2b_s9qh66r2pw0000gn/T/ipykernel_2015/759014450.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_epd_tmp['award_date']=df_epd_tmp['award_date1']

In [174]:
df_dsd=pd.read_json('gov_dsd.json',lines=True)

In [170]:
df_dsd.head()

,award_date,awardee,start,end,sum,project_office,department,type,url,ref
0,1 June 2026,REC Engineering Company Limited,14 August 2026,13 August 2029,"HK$270,230,462.00",Sewage Treatment Division 1,Drainage Services Department,Contract,https://www.dsd.gov.hk/EN/Our_Projects/Contrac...,DE/2026/08
1,21 May 2026,Shun Yuen Construction Company Limited,1 June 2026,31 May 2030,"HK$239,233,660.23",Hong Kong and Islands Division,Drainage Services Department,Contract,https://www.dsd.gov.hk/EN/Our_Projects/Contrac...,DC/2026/02
2,27 May 2026,Shun Yuen Construction Company Limited,1 June 2026,31 May 2030,"HK$249,708,314.23",Mainland North Division,Drainage Services Department,Contract,https://www.dsd.gov.hk/EN/Our_Projects/Contrac...,DE/2026/05
3,4 June 2026,EGIS-SMEDI Joint Venture,17 June 2026,17 October 2030,"HK$28,980,950.00",Cavern Projects Division,Drainage Services Department,Contract,https://www.dsd.gov.hk/EN/Our_Projects/Contrac...,DC/2025/10
4,27 May 2026,Dunwell Engineering Company Limited,10 June 2026,4 August 2027,"HK$8,900,000.00",Electrical and Mechanical Projects Division,Drainage Services Department,Consultancy,https://www.dsd.gov.hk/EN/Our_Projects/Contrac...,CE 38/2025 (SP)

In [178]:
df_dsd_tmp=df_dsd[["ref","department","description","awardee","award_date",	"sum","period","url","start","end"]]

In [193]:
df_dsd_tmp['award_date1']=''

for i in range(len(df_dsd_tmp)):
    df_dsd_tmp.loc[i,'award_date1']=datetime.strptime(df_dsd_tmp.loc[i,'award_date'], "%d %B %Y")
    df_dsd_tmp.loc[i,'start1']=datetime.strptime(df_dsd_tmp.loc[i,'start'], "%d %B %Y")
    df_dsd_tmp.loc[i,'end1']=datetime.strptime(df_dsd_tmp.loc[i,'end'], "%d %B %Y")

/var/folders/cc/fgdvcyz155z2b_s9qh66r2pw0000gn/T/ipykernel_2015/2585314945.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_dsd_tmp['award_date1']=''

In [197]:
df_dsd_tmp['award_date']=df_dsd_tmp['award_date1']
df_dsd_tmp['start']=df_dsd_tmp['start1']
df_dsd_tmp['end']=df_dsd_tmp['end1']

In [201]:
df_dsd_tmp=df_dsd_tmp[["ref","department","description","awardee","award_date",	"sum","period","url","start","end"]]

In [260]:
df_cedd=pd.read_json('gov_cedd.json',lines=True)

In [266]:
df_cedd_tmp=df_cedd[["ref","department","description","awardee","award_date",	"sum",#"period",
                     "url"#,"start","end"
                    ]]

In [268]:
df_cedd_tmp['award_date1']=''

for i in range(len(df_cedd_tmp)):
    df_cedd_tmp.loc[i,'award_date1']=datetime.strptime(df_cedd_tmp.loc[i,'award_date'], "%d/%m/%Y")

df_cedd_tmp['award_date']=df_cedd_tmp['award_date1']

/var/folders/cc/fgdvcyz155z2b_s9qh66r2pw0000gn/T/ipykernel_2015/2605515332.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_cedd_tmp['award_date1']=''
/var/folders/cc/fgdvcyz155z2b_s9qh66r2pw0000gn/T/ipykernel_2015/2605515332.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_cedd_tmp['award_date']=df_cedd_tmp['award_date1']

In [270]:
df_cedd_tmp=df_cedd_tmp[["ref","department","description","awardee","award_date",	"sum",#"period",
                     "url"#,"start","end"
                    ]]

In [272]:
df_cedd_tmp.head()

,ref,department,description,awardee,award_date,sum,url
0,Contract No.: CV/2025/02,Civil Engineering and Development Department,"Landslip Prevention and Mitigation Programme, ...",CM Geotechnics Limited,2026-07-29 00:00:00,HK$270.64,https://www.cedd.gov.hk//eng/tender-notices/co...
1,Contract No.: CEDD/S/T/1/2026,Civil Engineering and Development Department,"Landslip Prevention and Mitigation Programme, ...",Pan Kee Construction Limited,2026-07-14 00:00:00,HK$193.17,https://www.cedd.gov.hk//eng/tender-notices/co...
2,Contract No.: ND/2024/11,Civil Engineering and Development Department,"Landslip Prevention and Mitigation Programme, ...",Tysan Foundation Limited,2026-07-06 00:00:00,HK$32.03,https://www.cedd.gov.hk//eng/tender-notices/co...
3,Contract No.: GE/2025/29,Civil Engineering and Development Department,Tung Chung New Town Extension – Infrastructure...,CCC-CCECC-CR11G Joint Venture,2026-06-26 00:00:00,HK$792 million,https://www.cedd.gov.hk//eng/tender-notices/co...
4,Contract No.: YL/2024/03,Civil Engineering and Development Department,San Tin Technopole Phase 1 Stage 1 (East) – Co...,CRBC - MAYLON Joint Venture,2026-06-11 00:00:00,"HK$ 2,266.91",https://www.cedd.gov.hk//eng/tender-notices/co...

In [240]:
df_cedd_consultant=pd.read_json('gov_cedd_consultant.json',lines=True)

In [242]:
df_cedd_consultant_tmp=df_cedd_consultant[["ref","department","description","awardee","award_date",	"sum",#"period",
                     "url","start","end"
                    ]]

In [274]:
df_cedd_consultant_tmp['award_date1']=''
df_cedd_consultant_tmp['start1']=''
df_cedd_consultant_tmp['end1']=''

for i in range(len(df_cedd_consultant_tmp)):
    df_cedd_consultant_tmp.loc[i,'award_date1']=datetime.strptime(df_cedd_consultant_tmp.loc[i,'award_date'], "%d/%m/%Y")
    df_cedd_consultant_tmp.loc[i,'start1']=datetime.strptime(df_cedd_consultant_tmp.loc[i,'start'], "%d/%m/%Y")
    df_cedd_consultant_tmp.loc[i,'end1']=datetime.strptime(df_cedd_consultant_tmp.loc[i,'end'], "%d/%m/%Y")


df_cedd_consultant_tmp['award_date']=df_cedd_consultant_tmp['award_date1']
df_cedd_consultant_tmp['start']=df_cedd_consultant_tmp['start1']
df_cedd_consultant_tmp['end']=df_cedd_consultant_tmp['end1']

In [276]:
df_cedd_consultant_tmp=df_cedd_consultant_tmp[["ref","department","description","awardee","award_date",	"sum",#"period",
                     "url","start","end"
                    ]]

In [278]:
df_cedd_consultant_tmp.head()

,ref,department,description,awardee,award_date,sum,url,start,end
0,CE 16/2026 (CE),Civil Engineering and Development Department,Hung Shui Kiu/Ha Tsuen New Development Area Re...,Arup-AtkinsRéalis Joint Venture,2026-08-06 00:00:00,"HK$148,000,002.00",https://www.cedd.gov.hk/eng/tender-notices/con...,2026-08-10 00:00:00,2039-08-31 00:00:00
1,CE 1/2026 (CE),Civil Engineering and Development Department,The Establishment of an Agricultural Park (Pha...,Mott MacDonald Hong Kong Limited,2026-07-13 00:00:00,"HK$14,980,000.00",https://www.cedd.gov.hk/eng/tender-notices/con...,2026-07-17 00:00:00,2034-09-17 00:00:00
2,CE 39/2025 (CE),Civil Engineering and Development Department,Reclamation at Lung Kwu Tan - Design and Const...,Ove Arup & Partners Hong Kong Limited,2026-06-25 00:00:00,"HK$43,500,000.00",https://www.cedd.gov.hk/eng/tender-notices/con...,2026-06-30 00:00:00,2036-06-29 00:00:00
3,CE 18/2025 (GE),Civil Engineering and Development Department,"Landslip Prevention and Mitigation Programme, ...",Asia Infrastructure Solutions Limited,2026-03-20 00:00:00,"HK$25,500,000.00",https://www.cedd.gov.hk/eng/tender-notices/con...,2026-03-31 00:00:00,2032-03-30 00:00:00
4,CE 19/2025 (GE),Civil Engineering and Development Department,"Landslip Prevention and Mitigation Programme, ...",AECOM Asia Company Limited,2026-03-20 00:00:00,"HK$24,600,000.00",https://www.cedd.gov.hk/eng/tender-notices/con...,2026-03-31 00:00:00,2031-03-30 00:00:00

In [287]:
df_emsd=pd.read_json('gov_emsd.json',lines=True)

In [291]:
df_emsd_tmp=df_emsd[["ref","department","description","awardee","award_date",	"sum",#"period",
                     "url",#"start",
                                "end"
                    ]]

In [293]:
df_emsd_tmp.head()

,ref,department,description,awardee,award_date,sum,url,end
0,CE 40/2025 (CE),emsd,Development of Intelligent Solutions for Smart...,Asia Infrastructure Solutions Limited,27 March 2026,"HK$23,800,000.00",/filemanager/en/content_880/CE40_2025_CE-Inter...,7 April 2028
1,CE 39/2024 (EM),emsd,Monitoring of Electricity Supply Companies and...,AtkinsRealis Asia Limited,27 January 2026,"HK$11,030,991.00",/filemanager/en/content_880/CE39_2024_EM-Inter...,10 February 2030
2,CE 55/2023 (EM),emsd,"Replacement of High Voltage, Low Voltage and G...",Pypun-KD & Associates Limited,5 December 2024,"HK$7,380,000.00",/filemanager/en/content_409/EOI_Invitation_Let...,18 December 2028
3,CE 21/2023 (CE),emsd,The District Cooling System (DCS) for Hung Shu...,Binnies Hong Kong Limited,18 June 2024,"HK$50,000,000.00",/filemanager/en/content_409/CE21_2023(CE)_Noti...,31 December 2033
4,CE 28/2023 (EM),emsd,Replacement of Tunnel Lighting System at Tate'...,WSP (Asia) Limited,13 May 2024,"HK$4,828,800.00",/filemanager/en/content_409/EOI_Invitation Let...,27 May 2028

In [295]:
df_emsd_tmp['award_date1']=''
df_emsd_tmp['end1']=''

for i in range(len(df_cedd_consultant_tmp)):
    df_emsd_tmp.loc[i,'award_date1']=datetime.strptime(df_emsd_tmp.loc[i,'award_date'], "%d %B %Y")
    df_emsd_tmp.loc[i,'end1']=datetime.strptime(df_emsd_tmp.loc[i,'end'], "%d %B %Y")


df_emsd_tmp['award_date']=df_emsd_tmp['award_date1']
df_emsd_tmp['end']=df_emsd_tmp['end1']

In [297]:
df_emsd_tmp=df_emsd_tmp[["ref","department","description","awardee","award_date",	"sum",#"period",
                     "url",#"start",
                                "end"
                    ]]

In [318]:
df_emsd_construction=pd.read_json('gov_emsd_construction.json',lines=True)

In [322]:
df_emsd_construction_tmp=df_emsd_construction[["ref","department","description","awardee","award_date",	"sum",#"period",
                     "url"#,"start","end"
                    ]]

In [324]:
df_emsd_construction_tmp.head()

,ref,department,description,awardee,award_date,sum,url
0,1280EM25T,Electrical and Mechanical Services Department,Triennial Term Contract for the Comprehensive ...,Holake Hong Kong Lifts Limited,May 2026,Holake Hong Kong Lifts Limited,https://www.emsd.gov.hk/en/tenders_contracts_a...
1,1212EM25W,Electrical and Mechanical Services Department,Enhancement Works for Tunnel Ventilation Fans ...,The Jardine Engineering Corporation Limited,May 2026,The Jardine Engineering Corporation Limited,https://www.emsd.gov.hk/en/tenders_contracts_a...
2,ADM/T/2025/02,Electrical and Mechanical Services Department,Provision of Property Management Services to t...,Synergis Facility Management Limited,Apr 2026,Synergis Facility Management Limited,https://www.emsd.gov.hk/en/tenders_contracts_a...
3,1766EM24T,Electrical and Mechanical Services Department,Quinquennial Term Contract for Air-Conditionin...,Winston Air Conditioning & Engineering (Hong K...,Apr 2026,Winston Air Conditioning & Engineering (Hong K...,https://www.emsd.gov.hk/en/tenders_contracts_a...
4,1960EM25T,Electrical and Mechanical Services Department,"Quadrennial Term Contract for Repairs, Operati...",Kwong Hing Loong Engine & Boiler Factory Limited,Apr 2026,Kwong Hing Loong Engine & Boiler Factory Limited,https://www.emsd.gov.hk/en/tenders_contracts_a...

In [328]:
df_emsd_construction_tmp['award_date1']=''

for i in range(len(df_cedd_consultant_tmp)):
    df_emsd_construction_tmp.loc[i,'award_date1']=datetime.strptime(df_emsd_construction_tmp.loc[i,'award_date'], "%b %Y")


df_emsd_construction_tmp['award_date']=df_emsd_construction_tmp['award_date1']

/var/folders/cc/fgdvcyz155z2b_s9qh66r2pw0000gn/T/ipykernel_2015/500775801.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_emsd_construction_tmp['award_date1']=''
/var/folders/cc/fgdvcyz155z2b_s9qh66r2pw0000gn/T/ipykernel_2015/500775801.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_emsd_construction_tmp['award_date']=df_emsd_construction_tmp['award_date1']

In [330]:
df_emsd_construction_tmp=df_emsd_construction_tmp[["ref","department","description","awardee","award_date",	"sum",#"period",
                     "url"#,"start","end"
                    ]]

In [349]:
with open('gov_hkaa.json', 'r', encoding='utf-8') as file:
    df_hkaa = json.load(file)

JSONDecodeError: Extra data: line 2 column 1 (char 569)